### ISSUE TITLE
Design basic gameplay

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/koalagochi#1]
There should be a nice tamagochi-like gameplay for koalagochi, where the player should take care of his own koala
- **User actions:**
  - Feed
  - Poke
  - Let koala sleep (when user doesn't do anything after some time)
- **Koala states:**
  - Happy - everything good
  - Hungry - Needs eucalyptus
  - Sleepy - After a hard day, a koala needs to sleep
  - Angry - When you poke the koala

¿Anything else?

**Comment by andarilhoz** [comment]
I could do it, can i be in charge of this issue? (:

**Comment by angrykoala** [comment]
@andarilhoz this issue is mainly to discuss the gameplay, so if you have ideas or improvements, feel free to add comments or documents to this issue so we can discuss it

**Comment by andarilhoz** [comment]
Possible actions: play and bath
Possible states: bored and dirty

(:

**Comment by angrykoala** [comment]
Action: pet koala
State:
![](http://reactiongifs.me/wp-content/uploads/2014/03/happy-koala-shaking-ears-cute-ticklish-koala-bear-.gif)

**Comment by andarilhoz** [comment]
He could also have some bars, like life and hungry, that way we could know if he is full, sick, hungry and etc (:

**Comment by angrykoala** [comment]
@andarilhoz this is intended to be on a telegram bot, is it possible to add bars? or you mean ascii-style bars? (which could be cool actually)

**Comment by andarilhoz** [comment]
@angrykoala i was talking about the concept (having an int as life / hungry) but the ascii art would be really awesome xD

**Comment by angrykoala** [comment]
This issue will reamin open for some time for people to add ideas, but we can consider the basic gameplay to be defined

**Comment by angrykoala** [comment]
## Defined Gameplay
- **User actions:**
  - Feed
  - Poke
  - Let koala sleep (when user doesn't do anything after some time for example)
  - Bath
- **Koala states:**
  - Happy - Everything good
  - Hungry - Needs eucalyptus
  - Sleepy - After a hard day, a koala needs to sleep
  - Angry - When you poke the koala
  - Dirty

The states are defined by a number (0~100) for each state (except Happy), the user is able to see and change this values. This values will also change automatically with time (increasing or decreasing).

The koala will be happy when:
- Low hunger
- Low sleepiness
- Low angriness
- Low "dirtiness"

All the values will increase automatically except "angriness" which will decrease automatically
