### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/koalagochi#2]
A mongo database would be nice to store user's koalas

**Comment by pv2k** [comment]
Sorry to mind you, but what is a user koala???

**Comment by angrykoala** [comment]
@pv2k sorry, forgot to add the '

Basically, koalagochi is about taking care of a koala, so each user has a koala an it should be stored somewhere

**Comment by pv2k** [comment]
Sorry to mind @angrykoala can you briefly explain me what is a koala ????

**Comment by angrykoala** [comment]
@pv2k As will be discussed in #1 the game revolves around taking care of a koala-bear in a tamagochi style

Like this cool guy 
![](https://upload.wikimedia.org/wikipedia/commons/4/49/Koala_climbing_tree.jpg)

**Comment by pv2k** [comment]
What fields the database should contain???

**Comment by angrykoala** [comment]
I'm not sure yet, as the game is still being designed in #1 , but at the moment something like this:

``` js
chatId: {
   state: string,
   pokeCount: number,
   feedCount: number,
   lastLogin: number/date
}
```

**Comment by pv2k** [comment]
Ok after #1 gets completed, I will work on this. Is that okay with you???

**Comment by angrykoala** [comment]
@pv2k yeah, thats ok, but now we have a slight situation, we need (preferably) to constantly update some values every second or so. I would be better if that doesn't require a js loop querying and updated all elements every second. So we should investigate in databases with that pre-prorammed behavior

If there is a way to do it with mongo that would be great, if not maybe using events and triggers with _mysql_ this could work.

The main problem is updating a large number of elements every second in the database

**Comment by angrykoala** [comment]
Currently, the database schema defined in #1 should be something like this:

```
id: String //Chat Id
koalaStats: {
    sleep: Number,
    anger: Number,
    hunger: Number
}
```

This may change with some extra values, but the basic structure will be something like that, with one koalaStats per user

**Comment by angrykoala** [comment]
#1 will remain open for people to add ideas, but we can consider it finished
