### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/koalagochi#3]
Better readme and some stuff would be nice

**Comment by ghost** [comment]
@angrykoala Hey I'm up for this, just let me know how its done, I have never done this before, give me a link or something to how to contribute and what are the requirements? thanks

**Comment by SmoothHacker** [comment]
I can also help with this.

**Comment by yash1998** [comment]
The topic seems to be nice. I think I can contribute with this project. Please send the documentation asap ! Looking forward to do it.

**Comment by angrykoala** [comment]
Currently there is no documentation. (that may be another issue), as I'm still doing some research on telegram bot API. However, the current code is small enough to be easy to understand.

The issue #1 should be a good place to start designing the final gameplay
